/** HRMS employee directory — synced from Employee_Master_List.xlsx (STS26… IDs). */
export const employeesSeed = [
  {
    id: "STS26ASE001",
    name: "Admin",
    department: "Operations",
    designation: "ADMIN",
    status: "Active",
    email: "",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["Professional skills"],
    experienceYears: 1,
  },
  {
    id: "STS26HRM002",
    name: "G. Naidu",
    department: "HR",
    designation: "HRM",
    status: "HR Manager",
    email: "mighttians97@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["HR operations", "Talent management", "HRMS"],
    experienceYears: 8,
  },
  {
    id: "STS26ASE003",
    name: "Kesava",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "sakichennakesavulu5@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26ASE004",
    name: "K.d. Prasad",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "karedlaprasad13@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26ASE005",
    name: "M.k. Swamy",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "mareedukumarswamy@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26ASE006",
    name: "N.n.durgarao",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "ndrnimagadda@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26ASE007",
    name: "Swami Naidu",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "raghuramkedasu2002@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26BDE008",
    name: "Naveen Goud",
    department: "Business Development",
    designation: "BDE",
    status: "Active",
    email: "naveench9997@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["Business development", "Client outreach", "CRM"],
    experienceYears: 2,
  },
  {
    id: "STS26BDE009",
    name: "Srikanth",
    department: "Business Development",
    designation: "BDE",
    status: "Active",
    email: "sreekanthp98614@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["Business development", "Client outreach", "CRM"],
    experienceYears: 2,
  },
  {
    id: "STS26BDE010",
    name: "Suma",
    department: "Business Development",
    designation: "BDE",
    status: "Active",
    email: "boddapatisumasuma@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["Business development", "Client outreach", "CRM"],
    experienceYears: 2,
  },
  {
    id: "STS26BDE011",
    name: "Lavanya",
    department: "Business Development",
    designation: "BDE",
    status: "Active",
    email: "lavanyabypureddy61@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["Business development", "Client outreach", "CRM"],
    experienceYears: 2,
  },
  {
    id: "STS26ASE012",
    name: "Sunil",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "sunilkumarmelapu418@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26ASE013",
    name: "K. Bhaskar",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "bhaskark874@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26ASE014",
    name: "Dileep Kumar",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "dileepkumarg557@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26ASE015",
    name: "Phani Kumar",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "phaneendra@be6technologies.in",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26BOE016",
    name: "Pallavi",
    department: "Business Development",
    designation: "BDE",
    status: "Active",
    email: "pallavigandrothu007@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["Business development", "Client outreach", "CRM"],
    experienceYears: 2,
  },
  {
    id: "STS26ASE017",
    name: "K. Prasanthi",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "eluriprasanthi2016@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26ASE018",
    name: "Ayyappa Reddy",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "ayyappareddychalla7@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26ASE019",
    name: "Pushkarpushkarsai",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "pushkarpushkarsai2288@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26ASE020",
    name: "Rambabu",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "rambabugorli1@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "STS26BDE021",
    name: "Gowri",
    department: "Business Development",
    designation: "BDE",
    status: "Active",
    email: "gowrisudabattula836@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["Business development", "Client outreach", "CRM"],
    experienceYears: 2,
  },
  {
    id: "STS26ASE022",
    name: "J.prasad",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "varaprasadjujjuri@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2026-01-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
];

export const employeeShiftSeed = Object.fromEntries(
  employeesSeed.map((e) => [e.id, "morning"])
);
