/** HRMS employee directory — synced from company employee sheet (BE1999xxxx). */
export const employeesSeed = [
  {
    id: "BE19990002",
    name: "Kumar",
    department: "HR",
    designation: "HRM",
    status: "Active",
    email: "kumarhrmbe6@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["HR operations", "Talent management", "HRMS"],
    experienceYears: 8,
  },
  {
    id: "BE19990003",
    name: "Kesava",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "sakichennakesavulu5@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "BE19990005",
    name: "Uma",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "uma@be6technologies.in",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "BE19990006",
    name: "Venkata Sai",
    department: "Engineering",
    designation: "DEVELOPER",
    status: "Active",
    email: "venkatasai@be6technologies.in",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["Software development", "Collaboration", "Code quality"],
    experienceYears: 2,
  },
  {
    id: "BE19990012",
    name: "Naveen Goud",
    department: "Business Development",
    designation: "BDE",
    status: "Active",
    email: "naveench9997@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["Business development", "Client outreach", "CRM"],
    experienceYears: 2,
  },
  {
    id: "BE19990013",
    name: "Faizan Ali",
    department: "Engineering",
    designation: "DEVELOPER",
    status: "Active",
    email: "faizanali@be6technologies.in",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["Software development", "Collaboration", "Code quality"],
    experienceYears: 2,
  },
  {
    id: "BE19990015",
    name: "Pavani",
    department: "HR",
    designation: "HR",
    status: "Active",
    email: "pavanihr@be6technologies.in",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["HR operations", "Talent management", "HRMS"],
    experienceYears: 3,
  },
  {
    id: "BE19990016",
    name: "Suma",
    department: "Business Development",
    designation: "BDE",
    status: "Active",
    email: "boddapatisumasuma@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["Business development", "Client outreach", "CRM"],
    experienceYears: 2,
  },
  {
    id: "BE19990017",
    name: "Kumar Swamy",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "kumarswamy@be6technologies.in",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "BE19990021",
    name: "Phaneendra",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "phaneendra@be6technologies.in",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "BE19990022",
    name: "Durga Prasad",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "durgaprasad@be6technologies.in",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "BE19990023",
    name: "Raghu Ram",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "raghuramkedasu2002@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "BE19990027",
    name: "Kotha Nagaraju",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "nagaraju@be6technologies.in",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "BE19990028",
    name: "Sreekanth Pendluru",
    department: "Business Development",
    designation: "BDE",
    status: "Active",
    email: "sreekanthp98614@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["Business development", "Client outreach", "CRM"],
    experienceYears: 2,
  },
  {
    id: "BE19990030",
    name: "Naga Durga Rao",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "ndrnimmagadda@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
  {
    id: "BE19990031",
    name: "Lavanya Bypureddi",
    department: "Business Development",
    designation: "BDE",
    status: "Active",
    email: "lavanyabypureddy61@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["Business development", "Client outreach", "CRM"],
    experienceYears: 2,
  },
  {
    id: "BE19990033",
    name: "Dileep Kumar",
    department: "Learning & Development",
    designation: "ASSOCIATE TRAINEE",
    status: "Active",
    email: "dileepkumarg557@gmail.com",
    phone: "",
    location: "Hyderabad",
    joinedAt: "2024-06-01",
    skills: ["On-the-job training", "Fundamentals", "Team collaboration"],
    experienceYears: 0,
  },
];

export const employeeShiftSeed = Object.fromEntries(
  employeesSeed.map((e) => [e.id, "morning"])
);
