"use client";

import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { Download, Wallet, RefreshCw } from "lucide-react";
import * as React from "react";
import { apiFetch } from "@/lib/api";
import { useAuth } from "@/features/auth/useAuth";

type PayslipRow = {
  id: string;
  employeeId: string;
  employeeName: string;
  department: string;
  designation: string;
  month: string; // YYYY-MM
  currency: "INR";
  netPay: number;
  status: "Generated";
};

export default function EmployeePayslipsPage() {
  const auth = useAuth();
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [rows, setRows] = React.useState<PayslipRow[]>([]);
  const [downloadingId, setDownloadingId] = React.useState<string | null>(null);

  const load = React.useCallback(() => {
    if (!auth.hydrated || !auth.token) return;
    setLoading(true);
    setError(null);
    apiFetch<{ payslips: PayslipRow[] }>("/employee/payslips/mine", { token: auth.token })
      .then((r) => setRows(r.payslips ?? []))
      .catch((e) => setError(e instanceof Error ? e.message : "Failed to load payslips"))
      .finally(() => setLoading(false));
  }, [auth.hydrated, auth.token]);

  React.useEffect(() => {
    load();
  }, [load]);

  const download = React.useCallback(
    (id: string) => {
      if (!auth.token) return;
      setDownloadingId(id);
      setError(null);
      apiFetch<{ payslip: unknown }>(`/employee/payslips/${id}`, { token: auth.token })
        .then((r) => {
          const blob = new Blob([JSON.stringify((r as any)?.payslip ?? {}, null, 2)], {
            type: "application/json;charset=utf-8",
          });
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = `payslip-${id}.json`;
          a.click();
          URL.revokeObjectURL(url);
        })
        .catch((e) => setError(e instanceof Error ? e.message : "Failed to download payslip"))
        .finally(() => setDownloadingId(null));
    },
    [auth.token]
  );

  return (
    <DashboardShell role="employee" title="Payslips">
      <div className="glass rounded-3xl p-6">
        <div className="flex items-start justify-between gap-4">
          <div>
            <div className="text-base font-semibold">Payslips</div>
            <p className="mt-2 text-sm text-slate-300/85">
              View and download your monthly payslips (generated by Admin).
            </p>
          </div>
          <button
            type="button"
            onClick={load}
            className="inline-flex items-center gap-2 rounded-2xl px-4 py-2 text-sm font-semibold text-white bg-white/5 ring-1 ring-white/10 hover:bg-white/10 transition"
          >
            <RefreshCw className="h-4 w-4" />
            Refresh
          </button>
        </div>
        {error ? (
          <div className="mt-4 rounded-2xl bg-red-500/10 ring-1 ring-red-500/20 p-4 text-xs text-red-200/90">
            {error}
          </div>
        ) : null}
        <div className="mt-6 overflow-x-auto">
          <table className="min-w-[720px] w-full text-sm">
            <thead className="bg-white/5">
              <tr className="text-left text-slate-200/85">
                <th className="px-5 py-4">Month</th>
                <th className="px-5 py-4">Net Pay</th>
                <th className="px-5 py-4">Status</th>
                <th className="px-5 py-4">Action</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r) => (
                <tr key={r.id} className="border-t border-white/10">
                  <td className="px-5 py-4 font-semibold">{r.month}</td>
                  <td className="px-5 py-4 text-slate-200/85">
                    ₹ {Number(r.netPay ?? 0).toLocaleString("en-IN")}
                  </td>
                  <td className="px-5 py-4">
                    <span className="inline-flex items-center rounded-full px-3 py-1 text-xs bg-white/5 ring-1 ring-white/10">
                      {r.status}
                    </span>
                  </td>
                  <td className="px-5 py-4">
                    <button
                      type="button"
                      onClick={() => download(r.id)}
                      disabled={downloadingId === r.id}
                      className="inline-flex items-center gap-2 rounded-2xl px-3 py-2 text-xs font-semibold text-white bg-white/5 ring-1 ring-white/10 hover:bg-white/10 transition"
                    >
                      <Download className="h-4 w-4 text-[#F57C00]" />
                      {downloadingId === r.id ? "Downloading…" : "Download"}
                    </button>
                  </td>
                </tr>
              ))}
              {loading ? (
                <tr>
                  <td className="px-5 py-8 text-slate-300/70" colSpan={4}>
                    Loading…
                  </td>
                </tr>
              ) : null}
              {!loading && rows.length === 0 ? (
                <tr>
                  <td className="px-5 py-8 text-slate-300/70" colSpan={4}>
                    No payslips yet. Ask Admin to generate one.
                  </td>
                </tr>
              ) : null}
            </tbody>
          </table>
        </div>
        <div className="mt-6 rounded-3xl bg-white/5 ring-1 ring-white/10 p-5">
          <div className="flex items-center gap-2 text-sm font-semibold">
            <Wallet className="h-4 w-4 text-[#F57C00]" />
            Payroll notes
          </div>
          <div className="mt-2 text-sm text-slate-300/85">
            Payslips are protected by JWT. This demo downloads a JSON payslip file.
          </div>
        </div>
      </div>
    </DashboardShell>
  );
}

